---
name: Jacob J.
surname: Christensen
position: "PhD, Postdoctoral Researcher"
address: "Gaustadveien 23A, 0372 Oslo"
phone: +47 92 45 00 67
www: jjchristensen.netlify.com
email: "j.j.christensen@medisin.uio.no"
twitter: jacobjchr
github: jacobjchristensen
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load packages
library(vitae)
library(tidyverse)
library(readxl)

# Load CV database
cv_path <- "../CV-log.xlsx"
cv_sheets <- excel_sheets(cv_path)
cv_data <- cv_sheets %>% 
  map(~read_xlsx(path = cv_path, sheet = .x)) %>% 
  set_names(cv_sheets)

options(encoding = "UTF-8")
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
bibliography_entries("ChristensenJJ.bib")
```

