---
name: Jacob J.
surname: Christensen
position: "PhD, Postdoctoral Researcher"
address: "Gaustadveien 23A, 0372 Oslo"
phone: +47 92 45 00 67
www: jjchristensen.netlify.com
email: "j.j.christensen@medisin.uio.no"
twitter: jacobjchr
github: jacobjchristensen
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load packages
library(vitae)
library(tidyverse)
library(readxl)

# Load CV database
cv_path <- "../CV-log.xlsx"
cv_sheets <- excel_sheets(cv_path)
cv_data <- cv_sheets %>% 
  map(~read_xlsx(path = cv_path, sheet = .x)) %>% 
  set_names(cv_sheets)
```

 * I am a clinical dietitian and postdoctoral researcher at Oslo University Hospital and University of Oslo. 
 * My research interests include cardiovascular diseases, lipid metabolism, nutrition, genomics and data science.

# Education and authorization

```{r}
cv_data$education %>% 
  filter(Type %in% c("University education", "Post graduate education")) %>% 
  arrange(desc(Date_start), desc(Date_end)) %>% 
  detailed_entries(what = Degree, when = Year, with = Institution, where = Where, why = Details)
```

# Work experience

```{r}
cv_data$experience %>% 
  filter(Type %in% c("Professional Positions", "Research visit abroad")) %>% 
  arrange(desc(Date_start), desc(Date_end)) %>% 
  detailed_entries(what = Position, when = Year, with = Institution, where = Where, why = Details)
```

# Presentations

## Invited speaker

## Poster presentations

# Publications

```{r}
bibliography_entries("../ChristensenJJ.bib") %>% 
  arrange(desc(date))
```

